pipeline{
    agent {label 'master'}
    stages{
         stage('scm'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: 'main']], 
                extensions: [], 
                userRemoteConfigs: [[credentialsId: 'faa7509c-4a0f-4b59-89f6-f50fe0cf9857',
                url: 'https://github.com/manikumar9951/ansible-roles.git']]])
            }
        }
        stage('utility usage '){
            steps{
                script{
                    sh '''
                    sh usage.sh > output.txt
                    column -t -s "|" output.txt
                    
                    '''
                }
            }
        }
    }
}