pipeline{
    agent {label 'master'}
    environment {
        PATH = "$PATH:/usr/share/apache-maven/bin"
    }
    parameters {
        string(name: 'RELEASE_REPO', defaultValue: "libs-release", description: 'Repo for releses')
        string(name: 'SNAPSHOT_REPO', defaultValue: "libs-snapshot", description: 'Repo for snapshot releses')
        string(name: 'ART_VERSION', defaultValue: "20221229.101026-1", description: 'Repo for snapshot releses')
        
        
    }
    stages{
        stage('scm'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: 'main']], 
                extensions: [], 
                userRemoteConfigs: [[credentialsId: 'faa7509c-4a0f-4b59-89f6-f50fe0cf9857',
                url: 'https://github.com/manikumar9951/ansible-roles.git']]])
            }
        }
        stage('Artifactory-Configuration') {
            steps {
                rtMavenDeployer (
                    id: 'spc-deployer',
                    serverId: 'jfrog-artifactory',
                    releaseRepo: "${params.RELEASE_REPO}",
                    snapshotRepo: "${params.SNAPSHOT_REPO}"
                    
                )
            }
        }
        stage('Upload artifacts to jfrog') {
            steps {
                rtMavenRun (
                    // Tool name from Jenkins configuration.
                    tool: 'MVN_BUILD',
                    pom: 'pom.xml',
                    goals: 'install',
                    // Maven options.
                    deployerId: 'spc-deployer'
                )
            }
        }
        stage('Download artifacts to jfrog') {
            steps {
                rtDownload (
                 serverId: 'jfrog-artifactory',
                    spec: '''{
                        "files": [
                            {
                        "pattern": "/var/lib/jenkins/workspace/ansible-role-deployment/target/com/hello/HelloWorld/0.0.1-SNAPSHOT/HelloWorld-0.0.1-${ART_VERSION}.jar",
                            "target": "./"
                            }
                        ]
                    }''',
                )
            }
        }
        stage('Apache-Deploy'){
            steps{
               ansiblePlaybook credentialsId: 'ec2-user', extras: "-e version=${ART_VERSION}", disableHostKeyChecking: true, installation: 'ansible2', inventory: 'Inventory', playbook: 'playbook.yml'
            }
        }
    }
}
